package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.Date;

import org.hibernate.annotations.CreationTimestamp;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire", schema = "groupe02")
public class Commentaire implements java.io.Serializable {

    private int id;
    private String contenu;
    private User user;
    private Synthese synthese;
    private Date createdAt;

    public Commentaire() {
    }

    public Commentaire(String contenu, User user, Synthese synthese) {
        this.contenu = contenu;
        this.user = user;
        this.synthese = synthese;
    }

    public Commentaire(int id, String contenu, User user, Synthese synthese, Date createdAt) {
        this.id = id;
        this.contenu = contenu;
        this.user = user;
        this.synthese = synthese;
        this.createdAt = createdAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "contenu", nullable = false)
    public String getContenu() {
        return this.contenu;
    }

    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "synthese_id", nullable = false)
    public Synthese getSynthese() {
        return this.synthese;
    }

    public void setSynthese(Synthese synthese) {
        this.synthese = synthese;
    }

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, length = 19)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
