package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.Set;

/**
 * Cours generated by hbm2java
 */
@Entity
@Table(name = "cours", schema = "groupe02")
public class Cours implements java.io.Serializable {

    private int id;
    private String nom;
    // private Set<FavCours> favCourses = new HashSet<FavCours>(0);
    // private Set<TeacherToCours> teacherToCourses = new HashSet<TeacherToCours>(0);
    // private Set<CoursToFaculte> coursToFacultes = new HashSet<CoursToFaculte>(0);
    // private Set<Synthese> syntheses = new HashSet<Synthese>(0);

    public Cours() {
    }

    public Cours(int id, String nom) {
        this.id = id;
        this.nom = nom;
    }

    public Cours(int id, String nom, Set<FavCours> favCourses, Set<TeacherToCours> teacherToCourses,
            Set<CoursToFaculte> coursToFacultes, Set<Synthese> syntheses) {
        this.id = id;
        this.nom = nom;
        // this.favCourses = favCourses;
        // this.teacherToCourses = teacherToCourses;
        // this.coursToFacultes = coursToFacultes;
        // this.syntheses = syntheses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nom", nullable = false, length = 100)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    // LAZY loading : on ne charge les sous-informations que si on nous les demande
    // (opposé : EAGER)
    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
    // public Set<FavCours> getFavCourses() {
    //     return this.favCourses;
    // }

    // public void setFavCourses(Set<FavCours> favCourses) {
    //     this.favCourses = favCourses;
    // }

    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
    // public Set<TeacherToCours> getTeacherToCourses() {
    //     return this.teacherToCourses;
    // }

    // public void setTeacherToCourses(Set<TeacherToCours> teacherToCourses) {
    //     this.teacherToCourses = teacherToCourses;
    // }

    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
    // public Set<CoursToFaculte> getCoursToFacultes() {
    //     return this.coursToFacultes;
    // }

    // public void setCoursToFacultes(Set<CoursToFaculte> coursToFacultes) {
    //     this.coursToFacultes = coursToFacultes;
    // }

    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "cours")
    // public Set<Synthese> getSyntheses() {
    //     return this.syntheses;
    // }

    // public void setSyntheses(Set<Synthese> syntheses) {
    //     this.syntheses = syntheses;
    // }

}
