package Projet_groupe02.demo.model;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * CoursToFaculte generated by hbm2java
 */
@Entity
@Table(name = "cours_to_faculte", schema = "groupe02")
public class CoursToFaculte implements java.io.Serializable {

    private CoursToFaculteId id;
    private Cours cours;
    private Faculte faculte;

    public CoursToFaculte() {
    }

    public CoursToFaculte(CoursToFaculteId id, Cours cours, Faculte faculte) {
        this.id = id;
        this.cours = cours;
        this.faculte = faculte;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "coursId", column = @Column(name = "cours_id", nullable = false)),
            @AttributeOverride(name = "faculteId", column = @Column(name = "faculte_id", nullable = false)) })
    public CoursToFaculteId getId() {
        return this.id;
    }

    public void setId(CoursToFaculteId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cours_id", nullable = false, insertable = false, updatable = false)
    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "faculte_id", nullable = false, insertable = false, updatable = false)
    public Faculte getFaculte() {
        return this.faculte;
    }

    public void setFaculte(Faculte faculte) {
        this.faculte = faculte;
    }

}
