package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CoursToFaculteId generated by hbm2java
 * 
 * C'est une classe qui est définie pour les id composés
 */
@Embeddable
public class CoursToFaculteId  implements java.io.Serializable {


     private int coursId;
     private int faculteId;

    public CoursToFaculteId() {
    }

    public CoursToFaculteId(int coursId, int faculteId) {
       this.coursId = coursId;
       this.faculteId = faculteId;
    }
   


    @Column(name="cours_id", nullable=false)
    public int getCoursId() {
        return this.coursId;
    }
    
    public void setCoursId(int coursId) {
        this.coursId = coursId;
    }


    @Column(name="faculte_id", nullable=false)
    public int getFaculteId() {
        return this.faculteId;
    }
    
    public void setFaculteId(int faculteId) {
        this.faculteId = faculteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CoursToFaculteId) ) return false;
		 CoursToFaculteId castOther = ( CoursToFaculteId ) other; 
         
		 return (this.getCoursId()==castOther.getCoursId())
 && (this.getFaculteId()==castOther.getFaculteId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getCoursId();
        result = 37 * result + this.getFaculteId();
         return result;
   }   


}


