package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.Set;

/**
 * Faculte generated by hbm2java
 */
@Entity
@Table(name = "faculte", schema = "groupe02")
public class Faculte implements java.io.Serializable {

    private int id;
    private String nom;
    private String image;
    // private Set<CoursToFaculte> coursToFacultes = new HashSet<CoursToFaculte>(0);

    public Faculte() {
    }

    public Faculte(int id, String nom, String image) {
        this.id = id;
        this.nom = nom;
        this.image = image;
    }

    public Faculte(String nom, String image) {
        this.nom = nom;
        this.image = image;
    }

    public Faculte(int id, String nom, String image, Set<CoursToFaculte> coursToFacultes) {
        this.id = id;
        this.nom = nom;
        this.image = image;
        // this.coursToFacultes = coursToFacultes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nom", nullable = false, length = 100)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "image", nullable = false, length = 255)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "faculte")
    // public Set<CoursToFaculte> getCoursToFacultes() {
    //     return this.coursToFacultes;
    // }

    // public void setCoursToFacultes(Set<CoursToFaculte> coursToFacultes) {
    //     this.coursToFacultes = coursToFacultes;
    // }

}
