package Projet_groupe02.demo.model;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * FavCours generated by hbm2java
 */
@Entity
@Table(name = "fav_cours", schema = "groupe02")
public class FavCours implements java.io.Serializable {

    private FavCoursId id;
    private Cours cours;
    private User user;

    public FavCours() {
    }

    public FavCours(FavCoursId id, Cours cours, User user) {
        this.id = id;
        this.cours = cours;
        this.user = user;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "coursId", column = @Column(name = "cours_id", nullable = false)),
            @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
    public FavCoursId getId() {
        return this.id;
    }

    public void setId(FavCoursId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cours_id", nullable = false, insertable = false, updatable = false)
    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
