package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FavCoursId generated by hbm2java
 */
@Embeddable
public class FavCoursId  implements java.io.Serializable {


     private int coursId;
     private int userId;

    public FavCoursId() {
    }

    public FavCoursId(int coursId, int userId) {
       this.coursId = coursId;
       this.userId = userId;
    }
   


    @Column(name="cours_id", nullable=false)
    public int getCoursId() {
        return this.coursId;
    }
    
    public void setCoursId(int coursId) {
        this.coursId = coursId;
    }


    @Column(name="user_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavCoursId) ) return false;
		 FavCoursId castOther = ( FavCoursId ) other; 
         
		 return (this.getCoursId()==castOther.getCoursId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getCoursId();
        result = 37 * result + this.getUserId();
         return result;
   }   


}


