package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * FavSynthId generated by hbm2java
 */
@Embeddable
public class FavSynthId implements java.io.Serializable {

    private int synthId;
    private int userId;

    public FavSynthId() {
    }

    public FavSynthId(int synthId, int userId) {
        this.synthId = synthId;
        this.userId = userId;
    }

    @Column(name = "synth_id", nullable = false)
    public int getSynthId() {
        return this.synthId;
    }

    public void setSynthId(int synthId) {
        this.synthId = synthId;
    }

    @Column(name = "user_id", nullable = false)
    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FavSynthId))
            return false;
        FavSynthId castOther = (FavSynthId) other;

        return (this.getSynthId() == castOther.getSynthId())
                && (this.getUserId() == castOther.getUserId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSynthId();
        result = 37 * result + this.getUserId();
        return result;
    }

}
