package Projet_groupe02.demo.model;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * FavSynth generated by hbm2java
 */
@Entity
@Table(name = "fav_synth", schema = "groupe02")
public class FavSynth implements java.io.Serializable {

    private FavSynthId id;
    private Synthese synthese;
    private User user;

    public FavSynth() {
    }

    public FavSynth(FavSynthId id, Synthese synthese, User user) {
        this.id = id;
        this.synthese = synthese;
        this.user = user;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "synthId", column = @Column(name = "synth_id", nullable = false)),
            @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
    public FavSynthId getId() {
        return this.id;
    }

    public void setId(FavSynthId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "synth_id", nullable = false, insertable = false, updatable = false)
    public Synthese getSynthese() {
        return this.synthese;
    }

    public void setSynthese(Synthese synthese) {
        this.synthese = synthese;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

}
