package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.util.Set;

/**
 * Synthese generated by hbm2java
 */
@Entity
@Table(name = "synthese", schema = "groupe02")
public class Synthese implements java.io.Serializable {

    private int id;
    private Cours cours;
    private User user;
    private String nom;
    private String url;

    public Synthese() {
    }

    public Synthese(Cours cours, User user, String nom, String url) {
        this.cours = cours;
        this.user = user;
        this.nom = nom;
        this.url = url;
    }

    public Synthese(Cours cours, User user, String nom, Set<FavSynth> favSynths, String url) {
        this.cours = cours;
        this.user = user;
        this.nom = nom;
        this.url = url;
    }

    public Synthese(int id, Cours cours, User user, String nom, Set<FavSynth> favSynths, String url) {
        this.id = id;
        this.cours = cours;
        this.user = user;
        this.nom = nom;
        this.url = url;
    }

    public Synthese(int id, String nom, Cours cours, User user, String url) {
        this.id = id;
        this.nom = nom;
        this.cours = cours;
        this.user = user;
        this.url = url;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cours_id", nullable = false)
    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "nom", nullable = false, length = 100)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "url", nullable = false, length = 300)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url){
        this.url = url;
    }
}
