package Projet_groupe02.demo.model;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * TeacherToCours generated by hbm2java
 */
@Entity
@Table(name = "teacher_to_cours", schema = "groupe02")
public class TeacherToCours implements java.io.Serializable {

    private TeacherToCoursId id;
    private Cours cours;
    private Teacher teacher;

    public TeacherToCours() {
    }

    public TeacherToCours(TeacherToCoursId id, Cours cours, Teacher teacher) {
        this.id = id;
        this.cours = cours;
        this.teacher = teacher;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "coursId", column = @Column(name = "cours_id", nullable = false)),
            @AttributeOverride(name = "teacherId", column = @Column(name = "teacher_id", nullable = false)) })
    public TeacherToCoursId getId() {
        return this.id;
    }

    public void setId(TeacherToCoursId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cours_id", nullable = false, insertable = false, updatable = false)
    public Cours getCours() {
        return this.cours;
    }

    public void setCours(Cours cours) {
        this.cours = cours;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "teacher_id", nullable = false, insertable = false, updatable = false)
    public Teacher getTeacher() {
        return this.teacher;
    }

    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }

}
