package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * TeacherToCoursId generated by hbm2java
 */
@Embeddable
public class TeacherToCoursId implements java.io.Serializable {

    private int coursId;
    private int teacherId;

    public TeacherToCoursId() {
    }

    public TeacherToCoursId(int coursId, int teacherId) {
        this.coursId = coursId;
        this.teacherId = teacherId;
    }

    @Column(name = "cours_id", nullable = false)
    public int getCoursId() {
        return this.coursId;
    }

    public void setCoursId(int coursId) {
        this.coursId = coursId;
    }

    @Column(name = "teacher_id", nullable = false)
    public int getTeacherId() {
        return this.teacherId;
    }

    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof TeacherToCoursId))
            return false;
        TeacherToCoursId castOther = (TeacherToCoursId) other;

        return (this.getCoursId() == castOther.getCoursId())
                && (this.getTeacherId() == castOther.getTeacherId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getCoursId();
        result = 37 * result + this.getTeacherId();
        return result;
    }

}
