package Projet_groupe02.demo.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher", schema = "groupe02")
public class Teacher implements java.io.Serializable {

    private int id;
    private String nom;
    private String prenom;
    // private Set<TeacherToCours> teacherToCourses = new HashSet<TeacherToCours>(0);

    public Teacher() {
    }

    public Teacher(int id, String nom, String prenom) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
    }

    public Teacher(int id, String nom, String prenom, Set<TeacherToCours> teacherToCourses) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
        // this.teacherToCourses = teacherToCourses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nom", nullable = false, length = 100)
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "prenom", nullable = false, length = 100)
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    // @OneToMany(fetch = FetchType.LAZY, mappedBy = "teacher")
    // public Set<TeacherToCours> getTeacherToCourses() {
    //     return this.teacherToCourses;
    // }

    // public void setTeacherToCourses(Set<TeacherToCours> teacherToCourses) {
    //     this.teacherToCourses = teacherToCourses;
    // }

}
