# HSQLDB Configuration
hibernate.connection.driver_class=org.hsqldb.jdbc.JDBCDriver
hibernate.connection.url=jdbc:hsqldb:file:hsqldb/data/calcisoc;hsqldb.lock_file=false
hibernate.dialect=org.hibernate.dialect.HSQLDialect
hibernate.connection.username=${env:HIBERNATE_USERNAME}
hibernate.connection.password=${env:HIBERNATE_PASSWORD}
hibernate.default_schema=CALCISOC
hibernate.default_catalog=PUBLIC
hibernate.connection.autocommit=true
hibernate.format_sql=true

